/* Egg Mates: no Auth calls are made. A device-local identity is used instead. */
const $ = (s) => document.querySelector(s);
const root = $('#app');
const config = window.EGG_MATES_CONFIG || {};
const configured = config.supabaseUrl?.includes('supabase.co') && !config.supabaseUrl.includes('YOUR_') && config.supabaseAnonKey && !config.supabaseAnonKey.includes('YOUR_');
const db = configured ? window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey) : null;
let me = JSON.parse(localStorage.getItem('egg-mates-profile') || 'null');
let activeChannel, matchesChannel;

function uid(){ return crypto.randomUUID(); }
function esc(s=''){ const d=document.createElement('div'); d.textContent=s; return d.innerHTML; }
function toast(message){ const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),4200); }
function photo(url){return url || `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120"><rect width="100%" height="100%" fill="#f8cf63"/><text x="50%" y="59%" dominant-baseline="middle" text-anchor="middle" font-size="58">🥚</text></svg>`)}`;}
function icon(symbol){return `<span class="nav-icon" aria-hidden="true">${symbol}</span>`;}
function layout(content, navigation=true){root.innerHTML=`<div class="shell"><header class="top"><div class="brand"><i class="egg"></i>Egg Mates</div>${navigation&&me?`<div class="menu-wrap"><button class="menu-toggle" id="menu-toggle" aria-label="Open menu" aria-expanded="false" aria-controls="menu">⋮</button><nav class="menu" id="menu" aria-label="Egg Mates menu" role="menu"><p class="menu-label">Navigation</p><button role="menuitem" data-nav="new">${icon('👤+')}<span>New Eggmates</span></button><button role="menuitem" data-nav="mates">${icon('👥')}<span>My Eggmates</span></button><hr><p class="menu-label">Account Actions</p><button role="menuitem" data-nav="signout">${icon('⇥')}<span>Sign Out</span></button><button role="menuitem" class="delete-nav" data-nav="delete">${icon('🗑')}<span>Delete Account</span></button></nav></div>`:''}</header>${content}</div>`;const toggle=$('#menu-toggle'),menu=$('#menu');toggle?.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open);if(open)menu.querySelector('[role="menuitem"]')?.focus();});document.querySelectorAll('[data-nav]').forEach(button=>button.onclick=()=>navigate(button.dataset.nav));}
function navigate(action){if(action==='new'){dashboard().then(()=>setTimeout(()=>$('#code')?.focus(),0));return;}if(action==='mates'){dashboard().then(()=>setTimeout(()=>$('#mate-list')?.scrollIntoView({behavior:'smooth',block:'start'}),0));return;}if(action==='signout')return signOut();if(action==='delete')return deleteAccount();}
function signOut(){activeChannel?.unsubscribe();matchesChannel?.unsubscribe();localStorage.removeItem('egg-mates-profile');me=null;toast('You have been signed out.');authView();}
function ensureDb(){if(!db){toast('Add your Supabase URL and publishable key in supabase-config.js first.');return false;}return true;}

function authView(login=true){layout(`<section class="card auth"><h1>${login?'Welcome back':'Find your Egg Mate'}</h1><p>${login?'Sign in on this device to see your Egg Mates.':'A little profile makes the reveal more fun.'}</p><form id="auth-form">${!login?`<label class="field">Full name<input name="full_name" maxlength="80" required autocomplete="name"></label><label class="field">Profile photo<input name="photo" type="file" accept="image/*" required></label><label class="field">A short introduction<textarea name="bio" maxlength="240" placeholder="Tell your future Egg Mate a little about you…" required></textarea></label>`:''}<label class="field">Username<input name="username" pattern="[A-Za-z0-9_]{3,30}" title="3–30 letters, numbers, or underscores" required autocomplete="username" placeholder="egg_lover"></label><label class="field">Password<input name="password" type="password" minlength="4" required autocomplete="current-password"></label><button class="primary">${login?'Sign in':'Create my profile'}</button></form><p class="switch">${login?'New here?':'Already have a profile?'} <button class="link" id="switch">${login?'Create one':'Sign in'}</button></p></section>`,false);
 $('#switch').onclick=()=>authView(!login); $('#auth-form').onsubmit=e=>submitAuth(e,login);
}
async function fileData(file){return new Promise((ok,no)=>{if(!file)return ok('');const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file);});}
async function submitAuth(e,login){e.preventDefault();const f=new FormData(e.currentTarget), username=f.get('username').trim().toLowerCase(),password=f.get('password');
 if(login){const stored=JSON.parse(localStorage.getItem(`egg-mates-credentials:${username}`)||'null');if(!stored||stored.password!==password){toast('That username or password is not available on this device.');return;}me=stored.profile;localStorage.setItem('egg-mates-profile',JSON.stringify(me));dashboard();return;}
 if(!ensureDb())return; const existing=JSON.parse(localStorage.getItem(`egg-mates-credentials:${username}`)||'null');if(existing){toast('That username already exists on this device.');return;}const profile={id:uid(),username,full_name:f.get('full_name').trim(),bio:f.get('bio').trim(),photo_url:await fileData(f.get('photo'))};
 const {error}=await db.from('profiles').insert(profile);if(error){toast(error.code==='23505'?'That username is already taken.':error.message);return;}localStorage.setItem(`egg-mates-credentials:${username}`,JSON.stringify({password,profile}));localStorage.setItem('egg-mates-profile',JSON.stringify(profile));me=profile;dashboard();}

async function dashboard(){if(!me)return authView();activeChannel?.unsubscribe();layout(`<section class="dashboard"><h1>Hi, ${esc(me.full_name.split(' ')[0])} <span aria-hidden="true">👋</span></h1><p class="sub">Enter the code from your egg puff to find your match.</p><form class="codebox" id="code-form"><input id="code" required maxlength="40" placeholder="ENTER YOUR SECRET CODE" aria-label="Secret code"><button class="primary">Find my mate</button></form><h2 class="section-head">Your Egg Mates</h2><div id="mate-list" class="mate-list"><div class="empty">No Egg Mates yet. Your next secret code could change that.</div></div></section>`);$('#code-form').onsubmit=claimCode;await loadMates();matchesChannel?.unsubscribe();matchesChannel=db?.channel(`matches-${me.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'codes'},async ({new:code})=>{if(code.status!=='matched'||(code.user_id_1!==me.id&&code.user_id_2!==me.id))return;matchesChannel?.unsubscribe();const mateId=code.user_id_1===me.id?code.user_id_2:code.user_id_1;const {data:mate}=await db.from('profiles').select('*').eq('id',mateId).single();if(mate){celebrate();reveal(mate,code.chat_id);}}).subscribe();}
async function loadMates(){if(!ensureDb())return;const {data:codes,error}=await db.from('codes').select('*').or(`user_id_1.eq.${me.id},user_id_2.eq.${me.id}`).eq('status','matched').order('created_at',{ascending:false});if(error)return toast(error.message);const mates=[];for(const c of codes||[]){const person=c.user_id_1===me.id?c.user_id_2:c.user_id_1;const {data:p}=await db.from('profiles').select('*').eq('id',person).single();if(p)mates.push({p,c});}const node=$('#mate-list');node.innerHTML=mates.length?mates.map(({p,c})=>`<article class="mate"><img class="avatar" src="${photo(p.photo_url)}" alt="${esc(p.full_name)}"><div class="mate-info"><strong>${esc(p.full_name)}</strong><span>${esc(p.bio)||'Your Egg Mate'}</span></div><button class="chat-link" data-chat="${c.chat_id}" data-id="${p.id}">Chat</button></article>`).join(''):'<div class="empty">No Egg Mates yet. Your next secret code could change that.</div>';node.querySelectorAll('.chat-link').forEach(b=>b.onclick=()=>openChat(b.dataset.chat,b.dataset.id));}
async function claimCode(e){e.preventDefault();if(!ensureDb())return;const code=$('#code').value.trim().toUpperCase();if(code.length<3){toast('Please enter a valid secret code.');return;}const {data,error}=await db.rpc('claim_code',{p_code:code,p_user_id:me.id});if(error){toast(error.message.includes('already redeemed')?'This code has already been redeemed by two Egg Mates!':error.message);return;}if(data.status==='waiting'){toast('Code saved — we’ll show your Egg Mate here when they enter it.');$('#code').value='';return;}const mateId=data.user_id_1===me.id?data.user_id_2:data.user_id_1;const {data:mate,error:pErr}=await db.from('profiles').select('*').eq('id',mateId).single();if(pErr){toast('Your code matched, but the profile is still loading.');return dashboard();} celebrate();reveal(mate,data.chat_id);}
function celebrate(){const holder=$('#confetti');const colors=['#f7be39','#ee9141','#eb6b6b','#5aa17d','#7f8fe8','#fff'];for(let i=0;i<120;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=colors[i%colors.length];c.style.setProperty('--drift',(Math.random()*240-120)+'px');c.style.animationDelay=Math.random()*.35+'s';holder.append(c);setTimeout(()=>c.remove(),3000)} try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.setValueAtTime(610,a.currentTime);o.frequency.exponentialRampToValueAtTime(910,a.currentTime+.16);g.gain.setValueAtTime(.09,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.32);o.start();o.stop(a.currentTime+.32)}catch{}}
function reveal(mate,chatId){layout(`<section class="reveal"><p class="handle">YOUR SECRET CODE CONNECTED</p><h1 class="match-title">It’s a match!</h1><p class="sub">You and ${esc(mate.full_name)} found the same Egg Mate code.</p><div class="profiles"><article class="card profile-card"><img class="avatar" src="${photo(me.photo_url)}"><h2>${esc(me.full_name)}</h2><p class="handle">@${esc(me.username)}</p><p class="bio">${esc(me.bio)}</p></article><div class="heart">💛</div><article class="card profile-card"><img class="avatar" src="${photo(mate.photo_url)}"><h2>${esc(mate.full_name)}</h2><p class="handle">@${esc(mate.username)}</p><p class="bio">${esc(mate.bio)}</p></article></div><button class="primary" id="start-chat" style="max-width:300px">Start chatting</button></section>`);$('#start-chat').onclick=()=>openChat(chatId,mate.id);}
async function openChat(chatId,mateId){if(!ensureDb())return;const {data:mate}=await db.from('profiles').select('*').eq('id',mateId).single();layout(`<section class="chat"><div class="chat-header"><img class="avatar" src="${photo(mate?.photo_url)}"><div><h1>${esc(mate?.full_name||'Egg Mate')}</h1><span>@${esc(mate?.username||'')}</span></div><button class="quiet" id="back">Back</button></div><div class="messages" id="messages"></div><form class="send" id="send"><input maxlength="1000" required placeholder="Write a message…"><button class="primary">Send</button></form></section>`);$('#back').onclick=dashboard;$('#send').onsubmit=e=>sendMessage(e,chatId);await loadMessages(chatId);activeChannel?.unsubscribe();activeChannel=db.channel(`chat-${chatId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`chat_id=eq.${chatId}`},payload=>appendMessage(payload.new)).subscribe();}
async function loadMessages(chatId){const {data,error}=await db.from('messages').select('*').eq('chat_id',chatId).order('created_at');if(error)return toast(error.message);data.forEach(appendMessage);}
function appendMessage(m){if(document.querySelector(`[data-message="${m.id}"]`))return;const node=$('#messages');if(!node)return;node.insertAdjacentHTML('beforeend',`<div class="bubble ${m.sender_id===me.id?'mine':''}" data-message="${m.id}">${esc(m.body)}<small>${new Date(m.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>`);node.scrollTop=node.scrollHeight;}
async function sendMessage(e,chatId){e.preventDefault();const input=e.currentTarget.querySelector('input'),body=input.value.trim();if(!body)return;input.value='';const {error}=await db.from('messages').insert({chat_id:chatId,sender_id:me.id,body});if(error)toast(error.message);}
async function deleteAccount(){if(!confirm('Delete your Egg Mates profile permanently?'))return;if(db){await db.from('messages').delete().eq('sender_id',me.id);await db.from('profiles').delete().eq('id',me.id);}localStorage.removeItem(`egg-mates-credentials:${me.username}`);localStorage.removeItem('egg-mates-profile');me=null;activeChannel?.unsubscribe();toast('Your account has been deleted.');authView();}
me?dashboard():authView();
